# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457cd6e295897a983bd5c976d7cfb86e6b93daf55f2cd299a8158b3d40551a3f0f01dfb09e75a585fad9450305bfb460c668f2fc9435b8a0b3b590c58e143dad

test:
  secret_key_base: a6c22422813616f491cfb38c3605d82f36c6f32d4f1fd864fa66e81d0dd0c394a7aafe4692b256619b92bad948da1022a64cf21fc28222d8caef34fcbce84fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
